# Generated by Django 6.0.1 on 2026-06-17 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.roomtype'),
        ),
        migrations.AddField(
            model_name='reservationstatuslog',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationstatuslog',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['organization', 'property', 'status'], name='reservation_organiz_5ed3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'check_in', 'check_out'], name='reservation_propert_c20aaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_reservation_code'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservation_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reservationguest',
            constraint=models.UniqueConstraint(fields=('reservation', 'guest'), name='uniq_guest_per_reservation'),
        ),
        migrations.AddIndex(
            model_name='reservationroom',
            index=models.Index(fields=['room', 'reservation'], name='reservation_room_id_b773a6_idx'),
        ),
    ]
