# Generated by Django 6.0.1 on 2026-06-17 13:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order')], default='vacant_clean', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blocks', to='properties.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='rooms.room')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['room', 'start_date', 'end_date'], name='rooms_roomb_room_id_6c226b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['organization', 'property'], name='rooms_roomt_organiz_133c1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='uniq_roomtype_code_per_property'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['organization', 'property', 'status'], name='rooms_room_organiz_f54e70_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property', 'room_type'], name='rooms_room_propert_3dfac1_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'number'), name='uniq_room_number_per_property'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='uniq_rateplan_code_per_property'),
        ),
    ]
